version: '3.8'

services:
  
  books-api:
    image: my-books-image
    build:
      context: ./BooksApi/BooksApi  
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

 
  user-api:
    image: my-users-image
    build:
      context: ./UserApi/UserApi
      dockerfile: Dockerfile
    ports:
      - "8081:8080"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - books-api    